// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6e4f4065DecodeGithubComGodaddyXWalletAdapterTypes(in *jlexer.Lexer, out *BatchTransferRecipient) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6e4f4065EncodeGithubComGodaddyXWalletAdapterTypes(out *jwriter.Writer, in BatchTransferRecipient) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BatchTransferRecipient) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6e4f4065EncodeGithubComGodaddyXWalletAdapterTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchTransferRecipient) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6e4f4065EncodeGithubComGodaddyXWalletAdapterTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchTransferRecipient) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6e4f4065DecodeGithubComGodaddyXWalletAdapterTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchTransferRecipient) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6e4f4065DecodeGithubComGodaddyXWalletAdapterTypes(l, v)
}
func easyjson6e4f4065DecodeGithubComGodaddyXWalletAdapterTypes1(in *jlexer.Lexer, out *BatchRawRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "protocol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Protocol = string(in.String())
			}
		case "appId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AppID = string(in.String())
			}
		case "account":
			if in.IsNull() {
				in.Skip()
				out.Account = nil
			} else {
				if out.Account == nil {
					out.Account = new(AssetsAccount)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Account).UnmarshalEasyJSON(in)
				}
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "contractAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddress = string(in.String())
			}
		case "recipients":
			if in.IsNull() {
				in.Skip()
				out.Recipients = nil
			} else {
				in.Delim('[')
				if out.Recipients == nil {
					if !in.IsDelim(']') {
						out.Recipients = make([]BatchTransferRecipient, 0, 2)
					} else {
						out.Recipients = []BatchTransferRecipient{}
					}
				} else {
					out.Recipients = (out.Recipients)[:0]
				}
				for !in.IsDelim(']') {
					var v1 BatchTransferRecipient
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Recipients = append(out.Recipients, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.ExtParam = make(map[string]string)
				} else {
					out.ExtParam = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					(out.ExtParam)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		case "speedUp":
			if in.IsNull() {
				in.Skip()
				out.SpeedUp = nil
			} else {
				if out.SpeedUp == nil {
					out.SpeedUp = new(SpeedUp)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.SpeedUp).UnmarshalEasyJSON(in)
				}
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "txType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxType = int64(in.Int64())
			}
		case "reqSigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Required = uint64(in.Uint64())
			}
		case "createTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateTime = int64(in.Int64())
			}
		case "estimatedFees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EstimatedFees = string(in.String())
			}
		case "estimatedFeeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EstimatedFeeRate = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6e4f4065EncodeGithubComGodaddyXWalletAdapterTypes1(out *jwriter.Writer, in BatchRawRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Protocol != "" {
		const prefix string = ",\"protocol\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Protocol))
	}
	if in.AppID != "" {
		const prefix string = ",\"appId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.AppID))
	}
	{
		const prefix string = ",\"account\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		if in.Account == nil {
			out.RawString("null")
		} else {
			(*in.Account).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"contractAddress\":"
		out.RawString(prefix)
		out.String(string(in.ContractAddress))
	}
	{
		const prefix string = ",\"recipients\":"
		out.RawString(prefix)
		if in.Recipients == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.Recipients {
				if v3 > 0 {
					out.RawByte(',')
				}
				(v4).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if in.FeeRate != "" {
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	if len(in.ExtParam) != 0 {
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v5First := true
			for v5Name, v5Value := range in.ExtParam {
				if v5First {
					v5First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v5Name))
				out.RawByte(':')
				out.String(string(v5Value))
			}
			out.RawByte('}')
		}
	}
	if in.SpeedUp != nil {
		const prefix string = ",\"speedUp\":"
		out.RawString(prefix)
		(*in.SpeedUp).MarshalEasyJSON(out)
	}
	if in.Sid != "" {
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	if in.TxType != 0 {
		const prefix string = ",\"txType\":"
		out.RawString(prefix)
		out.Int64(int64(in.TxType))
	}
	if in.Required != 0 {
		const prefix string = ",\"reqSigs\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Required))
	}
	if in.CreateTime != 0 {
		const prefix string = ",\"createTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateTime))
	}
	if in.EstimatedFees != "" {
		const prefix string = ",\"estimatedFees\":"
		out.RawString(prefix)
		out.String(string(in.EstimatedFees))
	}
	if in.EstimatedFeeRate != "" {
		const prefix string = ",\"estimatedFeeRate\":"
		out.RawString(prefix)
		out.String(string(in.EstimatedFeeRate))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BatchRawRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6e4f4065EncodeGithubComGodaddyXWalletAdapterTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BatchRawRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6e4f4065EncodeGithubComGodaddyXWalletAdapterTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BatchRawRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6e4f4065DecodeGithubComGodaddyXWalletAdapterTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BatchRawRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6e4f4065DecodeGithubComGodaddyXWalletAdapterTypes1(l, v)
}
