// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes(in *jlexer.Lexer, out *UnscanRecord) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes(out *jwriter.Writer, in UnscanRecord) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UnscanRecord) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UnscanRecord) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UnscanRecord) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UnscanRecord) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes1(in *jlexer.Lexer, out *TxVerifyResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "verified":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Verified = bool(in.Bool())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "confirmations":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirmations = uint64(in.Uint64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "extractData":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ExtractData = make(map[string][]*TxExtractData)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 []*TxExtractData
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						in.Delim('[')
						if v1 == nil {
							if !in.IsDelim(']') {
								v1 = make([]*TxExtractData, 0, 8)
							} else {
								v1 = []*TxExtractData{}
							}
						} else {
							v1 = (v1)[:0]
						}
						for !in.IsDelim(']') {
							var v2 *TxExtractData
							if in.IsNull() {
								in.Skip()
								v2 = nil
							} else {
								if v2 == nil {
									v2 = new(TxExtractData)
								}
								if in.IsNull() {
									in.Skip()
								} else {
									(*v2).UnmarshalEasyJSON(in)
								}
							}
							v1 = append(v1, v2)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.ExtractData)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "contractReceipts":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ContractReceipts = make(map[string]*SmartContractReceipt)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 *SmartContractReceipt
					if in.IsNull() {
						in.Skip()
						v3 = nil
					} else {
						if v3 == nil {
							v3 = new(SmartContractReceipt)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v3).UnmarshalEasyJSON(in)
						}
					}
					(out.ContractReceipts)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes1(out *jwriter.Writer, in TxVerifyResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"verified\":"
		out.RawString(prefix)
		out.Bool(bool(in.Verified))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"confirmations\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Confirmations))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"extractData\":"
		out.RawString(prefix)
		if in.ExtractData == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.ExtractData {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				if v4Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v5, v6 := range v4Value {
						if v5 > 0 {
							out.RawByte(',')
						}
						if v6 == nil {
							out.RawString("null")
						} else {
							(*v6).MarshalEasyJSON(out)
						}
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"contractReceipts\":"
		out.RawString(prefix)
		if in.ContractReceipts == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v7First := true
			for v7Name, v7Value := range in.ContractReceipts {
				if v7First {
					v7First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v7Name))
				out.RawByte(':')
				if v7Value == nil {
					out.RawString("null")
				} else {
					(*v7Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxVerifyResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxVerifyResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxVerifyResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxVerifyResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes1(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes2(in *jlexer.Lexer, out *TxVerifyMatchResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "verified":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Verified = bool(in.Bool())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		case "mismatches":
			if in.IsNull() {
				in.Skip()
				out.Mismatches = nil
			} else {
				in.Delim('[')
				if out.Mismatches == nil {
					if !in.IsDelim(']') {
						out.Mismatches = make([]string, 0, 4)
					} else {
						out.Mismatches = []string{}
					}
				} else {
					out.Mismatches = (out.Mismatches)[:0]
				}
				for !in.IsDelim(']') {
					var v8 string
					if in.IsNull() {
						in.Skip()
					} else {
						v8 = string(in.String())
					}
					out.Mismatches = append(out.Mismatches, v8)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "chain":
			if in.IsNull() {
				in.Skip()
				out.Chain = nil
			} else {
				if out.Chain == nil {
					out.Chain = new(TxVerifyResult)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Chain).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes2(out *jwriter.Writer, in TxVerifyMatchResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix[1:])
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"verified\":"
		out.RawString(prefix)
		out.Bool(bool(in.Verified))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"mismatches\":"
		out.RawString(prefix)
		if in.Mismatches == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v9, v10 := range in.Mismatches {
				if v9 > 0 {
					out.RawByte(',')
				}
				out.String(string(v10))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"chain\":"
		out.RawString(prefix)
		if in.Chain == nil {
			out.RawString("null")
		} else {
			(*in.Chain).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxVerifyMatchResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxVerifyMatchResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxVerifyMatchResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxVerifyMatchResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes2(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes3(in *jlexer.Lexer, out *TxVerifyExpected) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "height":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Height = uint64(in.Uint64())
			}
		case "transfers":
			if in.IsNull() {
				in.Skip()
				out.Transfers = nil
			} else {
				in.Delim('[')
				if out.Transfers == nil {
					if !in.IsDelim(']') {
						out.Transfers = make([]*TxTransferExpected, 0, 8)
					} else {
						out.Transfers = []*TxTransferExpected{}
					}
				} else {
					out.Transfers = (out.Transfers)[:0]
				}
				for !in.IsDelim(']') {
					var v11 *TxTransferExpected
					if in.IsNull() {
						in.Skip()
						v11 = nil
					} else {
						if v11 == nil {
							v11 = new(TxTransferExpected)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v11).UnmarshalEasyJSON(in)
						}
					}
					out.Transfers = append(out.Transfers, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes3(out *jwriter.Writer, in TxVerifyExpected) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"height\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Height))
	}
	{
		const prefix string = ",\"transfers\":"
		out.RawString(prefix)
		if in.Transfers == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.Transfers {
				if v12 > 0 {
					out.RawByte(',')
				}
				if v13 == nil {
					out.RawString("null")
				} else {
					(*v13).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxVerifyExpected) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxVerifyExpected) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxVerifyExpected) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxVerifyExpected) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes3(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes4(in *jlexer.Lexer, out *TxTransferExpected) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contractAddr":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractAddr = string(in.String())
			}
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = string(in.String())
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = uint32(in.Uint32())
			}
		case "logIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LogIndex = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes4(out *jwriter.Writer, in TxTransferExpected) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contractAddr\":"
		out.RawString(prefix[1:])
		out.String(string(in.ContractAddr))
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.Decimals))
	}
	{
		const prefix string = ",\"logIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.LogIndex))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxTransferExpected) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxTransferExpected) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxTransferExpected) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxTransferExpected) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes4(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes5(in *jlexer.Lexer, out *TxOutPut) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Recharge":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Recharge).UnmarshalEasyJSON(in)
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes5(out *jwriter.Writer, in TxOutPut) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Recharge\":"
		out.RawString(prefix[1:])
		(in.Recharge).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxOutPut) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxOutPut) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxOutPut) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxOutPut) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes5(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes6(in *jlexer.Lexer, out *TxInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "SourceTxID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceTxID = string(in.String())
			}
		case "SourceIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceIndex = uint64(in.Uint64())
			}
		case "Recharge":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Recharge).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes6(out *jwriter.Writer, in TxInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SourceTxID\":"
		out.RawString(prefix[1:])
		out.String(string(in.SourceTxID))
	}
	{
		const prefix string = ",\"SourceIndex\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.SourceIndex))
	}
	{
		const prefix string = ",\"Recharge\":"
		out.RawString(prefix)
		(in.Recharge).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes6(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes7(in *jlexer.Lexer, out *TxExtractData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "txInputs":
			if in.IsNull() {
				in.Skip()
				out.TxInputs = nil
			} else {
				in.Delim('[')
				if out.TxInputs == nil {
					if !in.IsDelim(']') {
						out.TxInputs = make([]*TxInput, 0, 8)
					} else {
						out.TxInputs = []*TxInput{}
					}
				} else {
					out.TxInputs = (out.TxInputs)[:0]
				}
				for !in.IsDelim(']') {
					var v14 *TxInput
					if in.IsNull() {
						in.Skip()
						v14 = nil
					} else {
						if v14 == nil {
							v14 = new(TxInput)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v14).UnmarshalEasyJSON(in)
						}
					}
					out.TxInputs = append(out.TxInputs, v14)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "txOutputs":
			if in.IsNull() {
				in.Skip()
				out.TxOutputs = nil
			} else {
				in.Delim('[')
				if out.TxOutputs == nil {
					if !in.IsDelim(']') {
						out.TxOutputs = make([]*TxOutPut, 0, 8)
					} else {
						out.TxOutputs = []*TxOutPut{}
					}
				} else {
					out.TxOutputs = (out.TxOutputs)[:0]
				}
				for !in.IsDelim(']') {
					var v15 *TxOutPut
					if in.IsNull() {
						in.Skip()
						v15 = nil
					} else {
						if v15 == nil {
							v15 = new(TxOutPut)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v15).UnmarshalEasyJSON(in)
						}
					}
					out.TxOutputs = append(out.TxOutputs, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "transaction":
			if in.IsNull() {
				in.Skip()
				out.Transaction = nil
			} else {
				if out.Transaction == nil {
					out.Transaction = new(Transaction)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Transaction).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes7(out *jwriter.Writer, in TxExtractData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"txInputs\":"
		out.RawString(prefix[1:])
		if in.TxInputs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.TxInputs {
				if v16 > 0 {
					out.RawByte(',')
				}
				if v17 == nil {
					out.RawString("null")
				} else {
					(*v17).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"txOutputs\":"
		out.RawString(prefix)
		if in.TxOutputs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.TxOutputs {
				if v18 > 0 {
					out.RawByte(',')
				}
				if v19 == nil {
					out.RawString("null")
				} else {
					(*v19).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"transaction\":"
		out.RawString(prefix)
		if in.Transaction == nil {
			out.RawString("null")
		} else {
			(*in.Transaction).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxExtractData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxExtractData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxExtractData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxExtractData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes7(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes8(in *jlexer.Lexer, out *SmartContractReceipt) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "wxid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WxID = string(in.String())
			}
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "rawReceipt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawReceipt = string(in.String())
			}
		case "events":
			if in.IsNull() {
				in.Skip()
				out.Events = nil
			} else {
				in.Delim('[')
				if out.Events == nil {
					if !in.IsDelim(']') {
						out.Events = make([]*SmartContractEvent, 0, 8)
					} else {
						out.Events = []*SmartContractEvent{}
					}
				} else {
					out.Events = (out.Events)[:0]
				}
				for !in.IsDelim(']') {
					var v20 *SmartContractEvent
					if in.IsNull() {
						in.Skip()
						v20 = nil
					} else {
						if v20 == nil {
							v20 = new(SmartContractEvent)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v20).UnmarshalEasyJSON(in)
						}
					}
					out.Events = append(out.Events, v20)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "confirmTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmTime = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.ExtParam = make(map[string]string)
				} else {
					out.ExtParam = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v21 string
					if in.IsNull() {
						in.Skip()
					} else {
						v21 = string(in.String())
					}
					(out.ExtParam)[key] = v21
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes8(out *jwriter.Writer, in SmartContractReceipt) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix[1:])
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"wxid\":"
		out.RawString(prefix)
		out.String(string(in.WxID))
	}
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"rawReceipt\":"
		out.RawString(prefix)
		out.String(string(in.RawReceipt))
	}
	{
		const prefix string = ",\"events\":"
		out.RawString(prefix)
		if in.Events == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v22, v23 := range in.Events {
				if v22 > 0 {
					out.RawByte(',')
				}
				if v23 == nil {
					out.RawString("null")
				} else {
					(*v23).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"confirmTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.ConfirmTime))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	if len(in.ExtParam) != 0 {
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v24First := true
			for v24Name, v24Value := range in.ExtParam {
				if v24First {
					v24First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v24Name))
				out.RawByte(':')
				out.String(string(v24Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SmartContractReceipt) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SmartContractReceipt) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SmartContractReceipt) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SmartContractReceipt) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes8(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes9(in *jlexer.Lexer, out *SmartContractEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contract":
			if in.IsNull() {
				in.Skip()
				out.Contract = nil
			} else {
				if out.Contract == nil {
					out.Contract = new(SmartContract)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Contract).UnmarshalEasyJSON(in)
				}
			}
		case "event":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Event = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes9(out *jwriter.Writer, in SmartContractEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contract\":"
		out.RawString(prefix[1:])
		if in.Contract == nil {
			out.RawString("null")
		} else {
			(*in.Contract).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"event\":"
		out.RawString(prefix)
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SmartContractEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SmartContractEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SmartContractEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SmartContractEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes9(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes10(in *jlexer.Lexer, out *ScanTargetResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "SourceKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceKey = string(in.String())
			}
		case "Exist":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Exist = bool(in.Bool())
			}
		case "TargetInfo":
			if m, ok := out.TargetInfo.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.TargetInfo.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.TargetInfo = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes10(out *jwriter.Writer, in ScanTargetResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SourceKey\":"
		out.RawString(prefix[1:])
		out.String(string(in.SourceKey))
	}
	{
		const prefix string = ",\"Exist\":"
		out.RawString(prefix)
		out.Bool(bool(in.Exist))
	}
	{
		const prefix string = ",\"TargetInfo\":"
		out.RawString(prefix)
		if m, ok := in.TargetInfo.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.TargetInfo.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.TargetInfo))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScanTargetResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScanTargetResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScanTargetResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScanTargetResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes10(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes11(in *jlexer.Lexer, out *ScanTargetParam) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ScanTarget":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ScanTarget = string(in.String())
			}
		case "Symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "ScanTargetType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ScanTargetType = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes11(out *jwriter.Writer, in ScanTargetParam) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ScanTarget\":"
		out.RawString(prefix[1:])
		out.String(string(in.ScanTarget))
	}
	{
		const prefix string = ",\"Symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"ScanTargetType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.ScanTargetType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScanTargetParam) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScanTargetParam) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScanTargetParam) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScanTargetParam) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes11(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes12(in *jlexer.Lexer, out *ScanTarget) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "PublicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "Alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "Symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "BalanceModelType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BalanceModelType = BalanceModelType(in.Uint32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes12(out *jwriter.Writer, in ScanTarget) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Address\":"
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"PublicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"Alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"Symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"BalanceModelType\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.BalanceModelType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScanTarget) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScanTarget) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScanTarget) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScanTarget) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes12(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes13(in *jlexer.Lexer, out *Recharge) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "confirm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirm = int64(in.Int64())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = uint64(in.Uint64())
			}
		case "createdAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateAt = int64(in.Int64())
			}
		case "txType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxType = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes13(out *jwriter.Writer, in Recharge) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"confirm\":"
		out.RawString(prefix)
		out.Int64(int64(in.Confirm))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Index))
	}
	{
		const prefix string = ",\"createdAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateAt))
	}
	{
		const prefix string = ",\"txType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TxType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Recharge) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Recharge) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Recharge) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Recharge) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes13(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes14(in *jlexer.Lexer, out *BlockchainSyncStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "NetworkBlockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NetworkBlockHeight = uint64(in.Uint64())
			}
		case "CurrentBlockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CurrentBlockHeight = uint64(in.Uint64())
			}
		case "Syncing":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Syncing = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes14(out *jwriter.Writer, in BlockchainSyncStatus) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"NetworkBlockHeight\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.NetworkBlockHeight))
	}
	{
		const prefix string = ",\"CurrentBlockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.CurrentBlockHeight))
	}
	{
		const prefix string = ",\"Syncing\":"
		out.RawString(prefix)
		out.Bool(bool(in.Syncing))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BlockchainSyncStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BlockchainSyncStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BlockchainSyncStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BlockchainSyncStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes14(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes15(in *jlexer.Lexer, out *BlockScanResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "height":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Height = uint64(in.Uint64())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "success":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Success = bool(in.Bool())
			}
		case "errorReason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ErrorReason = string(in.String())
			}
		case "txTotal":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxTotal = uint64(in.Uint64())
			}
		case "txFailed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxFailed = uint64(in.Uint64())
			}
		case "extractedTxs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtractedTxs = uint64(in.Uint64())
			}
		case "failedTxIDs":
			if in.IsNull() {
				in.Skip()
				out.FailedTxIDs = nil
			} else {
				in.Delim('[')
				if out.FailedTxIDs == nil {
					if !in.IsDelim(']') {
						out.FailedTxIDs = make([]string, 0, 4)
					} else {
						out.FailedTxIDs = []string{}
					}
				} else {
					out.FailedTxIDs = (out.FailedTxIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v25 string
					if in.IsNull() {
						in.Skip()
					} else {
						v25 = string(in.String())
					}
					out.FailedTxIDs = append(out.FailedTxIDs, v25)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "header":
			if in.IsNull() {
				in.Skip()
				out.Header = nil
			} else {
				if out.Header == nil {
					out.Header = new(BlockHeader)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Header).UnmarshalEasyJSON(in)
				}
			}
		case "extractData":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ExtractData = make(map[string][]*TxExtractData)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v26 []*TxExtractData
					if in.IsNull() {
						in.Skip()
						v26 = nil
					} else {
						in.Delim('[')
						if v26 == nil {
							if !in.IsDelim(']') {
								v26 = make([]*TxExtractData, 0, 8)
							} else {
								v26 = []*TxExtractData{}
							}
						} else {
							v26 = (v26)[:0]
						}
						for !in.IsDelim(']') {
							var v27 *TxExtractData
							if in.IsNull() {
								in.Skip()
								v27 = nil
							} else {
								if v27 == nil {
									v27 = new(TxExtractData)
								}
								if in.IsNull() {
									in.Skip()
								} else {
									(*v27).UnmarshalEasyJSON(in)
								}
							}
							v26 = append(v26, v27)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.ExtractData)[key] = v26
					in.WantComma()
				}
				in.Delim('}')
			}
		case "contractReceipts":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ContractReceipts = make(map[string]*SmartContractReceipt)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v28 *SmartContractReceipt
					if in.IsNull() {
						in.Skip()
						v28 = nil
					} else {
						if v28 == nil {
							v28 = new(SmartContractReceipt)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v28).UnmarshalEasyJSON(in)
						}
					}
					(out.ContractReceipts)[key] = v28
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes15(out *jwriter.Writer, in BlockScanResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"height\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Height))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"success\":"
		out.RawString(prefix)
		out.Bool(bool(in.Success))
	}
	{
		const prefix string = ",\"errorReason\":"
		out.RawString(prefix)
		out.String(string(in.ErrorReason))
	}
	{
		const prefix string = ",\"txTotal\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TxTotal))
	}
	{
		const prefix string = ",\"txFailed\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TxFailed))
	}
	{
		const prefix string = ",\"extractedTxs\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.ExtractedTxs))
	}
	{
		const prefix string = ",\"failedTxIDs\":"
		out.RawString(prefix)
		if in.FailedTxIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v29, v30 := range in.FailedTxIDs {
				if v29 > 0 {
					out.RawByte(',')
				}
				out.String(string(v30))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"header\":"
		out.RawString(prefix)
		if in.Header == nil {
			out.RawString("null")
		} else {
			(*in.Header).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"extractData\":"
		out.RawString(prefix)
		if in.ExtractData == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v31First := true
			for v31Name, v31Value := range in.ExtractData {
				if v31First {
					v31First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v31Name))
				out.RawByte(':')
				if v31Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v32, v33 := range v31Value {
						if v32 > 0 {
							out.RawByte(',')
						}
						if v33 == nil {
							out.RawString("null")
						} else {
							(*v33).MarshalEasyJSON(out)
						}
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"contractReceipts\":"
		out.RawString(prefix)
		if in.ContractReceipts == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v34First := true
			for v34Name, v34Value := range in.ContractReceipts {
				if v34First {
					v34First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v34Name))
				out.RawByte(':')
				if v34Value == nil {
					out.RawString("null")
				} else {
					(*v34Value).MarshalEasyJSON(out)
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BlockScanResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BlockScanResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BlockScanResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BlockScanResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes15(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes16(in *jlexer.Lexer, out *BlockHeader) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "hash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Hash = string(in.String())
			}
		case "confirmations":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirmations = uint64(in.Uint64())
			}
		case "merkleroot":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Merkleroot = string(in.String())
			}
		case "previousblockhash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Previousblockhash = string(in.String())
			}
		case "height":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Height = uint64(in.Uint64())
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = uint64(in.Uint64())
			}
		case "time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = uint64(in.Uint64())
			}
		case "fork":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fork = bool(in.Bool())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes16(out *jwriter.Writer, in BlockHeader) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"hash\":"
		out.RawString(prefix[1:])
		out.String(string(in.Hash))
	}
	{
		const prefix string = ",\"confirmations\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Confirmations))
	}
	{
		const prefix string = ",\"merkleroot\":"
		out.RawString(prefix)
		out.String(string(in.Merkleroot))
	}
	{
		const prefix string = ",\"previousblockhash\":"
		out.RawString(prefix)
		out.String(string(in.Previousblockhash))
	}
	{
		const prefix string = ",\"height\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Height))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Version))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Time))
	}
	{
		const prefix string = ",\"fork\":"
		out.RawString(prefix)
		out.Bool(bool(in.Fork))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BlockHeader) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes16(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BlockHeader) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes16(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BlockHeader) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes16(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BlockHeader) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes16(l, v)
}
func easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes17(in *jlexer.Lexer, out *Balance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "confirmBalance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmBalance = string(in.String())
			}
		case "unconfirmBalance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnconfirmBalance = string(in.String())
			}
		case "balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes17(out *jwriter.Writer, in Balance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"confirmBalance\":"
		out.RawString(prefix)
		out.String(string(in.ConfirmBalance))
	}
	{
		const prefix string = ",\"unconfirmBalance\":"
		out.RawString(prefix)
		out.String(string(in.UnconfirmBalance))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.String(string(in.Balance))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Balance) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes17(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Balance) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComGodaddyXWalletAdapterTypes17(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Balance) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes17(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Balance) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComGodaddyXWalletAdapterTypes17(l, v)
}
