// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes(in *jlexer.Lexer, out *UnscanRecord) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes(out *jwriter.Writer, in UnscanRecord) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UnscanRecord) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UnscanRecord) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UnscanRecord) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UnscanRecord) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes1(in *jlexer.Lexer, out *TxOutPut) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Recharge":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Recharge).UnmarshalEasyJSON(in)
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes1(out *jwriter.Writer, in TxOutPut) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Recharge\":"
		out.RawString(prefix[1:])
		(in.Recharge).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxOutPut) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxOutPut) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxOutPut) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxOutPut) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes1(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes2(in *jlexer.Lexer, out *TxInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "SourceTxID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceTxID = string(in.String())
			}
		case "SourceIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceIndex = uint64(in.Uint64())
			}
		case "Recharge":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Recharge).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes2(out *jwriter.Writer, in TxInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SourceTxID\":"
		out.RawString(prefix[1:])
		out.String(string(in.SourceTxID))
	}
	{
		const prefix string = ",\"SourceIndex\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.SourceIndex))
	}
	{
		const prefix string = ",\"Recharge\":"
		out.RawString(prefix)
		(in.Recharge).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes2(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes3(in *jlexer.Lexer, out *TxExtractData) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "txInputs":
			if in.IsNull() {
				in.Skip()
				out.TxInputs = nil
			} else {
				in.Delim('[')
				if out.TxInputs == nil {
					if !in.IsDelim(']') {
						out.TxInputs = make([]*TxInput, 0, 8)
					} else {
						out.TxInputs = []*TxInput{}
					}
				} else {
					out.TxInputs = (out.TxInputs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *TxInput
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(TxInput)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v1).UnmarshalEasyJSON(in)
						}
					}
					out.TxInputs = append(out.TxInputs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "txOutputs":
			if in.IsNull() {
				in.Skip()
				out.TxOutputs = nil
			} else {
				in.Delim('[')
				if out.TxOutputs == nil {
					if !in.IsDelim(']') {
						out.TxOutputs = make([]*TxOutPut, 0, 8)
					} else {
						out.TxOutputs = []*TxOutPut{}
					}
				} else {
					out.TxOutputs = (out.TxOutputs)[:0]
				}
				for !in.IsDelim(']') {
					var v2 *TxOutPut
					if in.IsNull() {
						in.Skip()
						v2 = nil
					} else {
						if v2 == nil {
							v2 = new(TxOutPut)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v2).UnmarshalEasyJSON(in)
						}
					}
					out.TxOutputs = append(out.TxOutputs, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "transaction":
			if in.IsNull() {
				in.Skip()
				out.Transaction = nil
			} else {
				if out.Transaction == nil {
					out.Transaction = new(Transaction)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Transaction).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes3(out *jwriter.Writer, in TxExtractData) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"txInputs\":"
		out.RawString(prefix[1:])
		if in.TxInputs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.TxInputs {
				if v3 > 0 {
					out.RawByte(',')
				}
				if v4 == nil {
					out.RawString("null")
				} else {
					(*v4).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"txOutputs\":"
		out.RawString(prefix)
		if in.TxOutputs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.TxOutputs {
				if v5 > 0 {
					out.RawByte(',')
				}
				if v6 == nil {
					out.RawString("null")
				} else {
					(*v6).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"transaction\":"
		out.RawString(prefix)
		if in.Transaction == nil {
			out.RawString("null")
		} else {
			(*in.Transaction).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TxExtractData) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TxExtractData) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TxExtractData) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TxExtractData) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes3(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes4(in *jlexer.Lexer, out *SmartContractReceipt) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "wxid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WxID = string(in.String())
			}
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "from":
			if in.IsNull() {
				in.Skip()
			} else {
				out.From = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				out.To = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "rawReceipt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawReceipt = string(in.String())
			}
		case "events":
			if in.IsNull() {
				in.Skip()
				out.Events = nil
			} else {
				in.Delim('[')
				if out.Events == nil {
					if !in.IsDelim(']') {
						out.Events = make([]*SmartContractEvent, 0, 8)
					} else {
						out.Events = []*SmartContractEvent{}
					}
				} else {
					out.Events = (out.Events)[:0]
				}
				for !in.IsDelim(']') {
					var v7 *SmartContractEvent
					if in.IsNull() {
						in.Skip()
						v7 = nil
					} else {
						if v7 == nil {
							v7 = new(SmartContractEvent)
						}
						if in.IsNull() {
							in.Skip()
						} else {
							(*v7).UnmarshalEasyJSON(in)
						}
					}
					out.Events = append(out.Events, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "confirmTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmTime = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes4(out *jwriter.Writer, in SmartContractReceipt) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix[1:])
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"wxid\":"
		out.RawString(prefix)
		out.String(string(in.WxID))
	}
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"rawReceipt\":"
		out.RawString(prefix)
		out.String(string(in.RawReceipt))
	}
	{
		const prefix string = ",\"events\":"
		out.RawString(prefix)
		if in.Events == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Events {
				if v8 > 0 {
					out.RawByte(',')
				}
				if v9 == nil {
					out.RawString("null")
				} else {
					(*v9).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"confirmTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.ConfirmTime))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SmartContractReceipt) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SmartContractReceipt) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SmartContractReceipt) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SmartContractReceipt) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes4(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes5(in *jlexer.Lexer, out *SmartContractEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contract":
			if in.IsNull() {
				in.Skip()
				out.Contract = nil
			} else {
				if out.Contract == nil {
					out.Contract = new(SmartContract)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Contract).UnmarshalEasyJSON(in)
				}
			}
		case "event":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Event = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes5(out *jwriter.Writer, in SmartContractEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contract\":"
		out.RawString(prefix[1:])
		if in.Contract == nil {
			out.RawString("null")
		} else {
			(*in.Contract).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"event\":"
		out.RawString(prefix)
		out.String(string(in.Event))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SmartContractEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SmartContractEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SmartContractEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SmartContractEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes5(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes6(in *jlexer.Lexer, out *ScanTargetResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "SourceKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SourceKey = string(in.String())
			}
		case "Exist":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Exist = bool(in.Bool())
			}
		case "TargetInfo":
			if m, ok := out.TargetInfo.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.TargetInfo.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.TargetInfo = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes6(out *jwriter.Writer, in ScanTargetResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"SourceKey\":"
		out.RawString(prefix[1:])
		out.String(string(in.SourceKey))
	}
	{
		const prefix string = ",\"Exist\":"
		out.RawString(prefix)
		out.Bool(bool(in.Exist))
	}
	{
		const prefix string = ",\"TargetInfo\":"
		out.RawString(prefix)
		if m, ok := in.TargetInfo.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.TargetInfo.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.TargetInfo))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScanTargetResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScanTargetResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScanTargetResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScanTargetResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes6(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes7(in *jlexer.Lexer, out *ScanTargetParam) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ScanTarget":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ScanTarget = string(in.String())
			}
		case "Symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "ScanTargetType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ScanTargetType = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes7(out *jwriter.Writer, in ScanTargetParam) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ScanTarget\":"
		out.RawString(prefix[1:])
		out.String(string(in.ScanTarget))
	}
	{
		const prefix string = ",\"Symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"ScanTargetType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.ScanTargetType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScanTargetParam) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScanTargetParam) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScanTargetParam) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScanTargetParam) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes7(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes8(in *jlexer.Lexer, out *ScanTarget) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "Address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "PublicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "Alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "Symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "BalanceModelType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BalanceModelType = BalanceModelType(in.Uint32())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes8(out *jwriter.Writer, in ScanTarget) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"Address\":"
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"PublicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"Alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"Symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"BalanceModelType\":"
		out.RawString(prefix)
		out.Uint32(uint32(in.BalanceModelType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ScanTarget) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ScanTarget) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ScanTarget) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ScanTarget) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes8(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes9(in *jlexer.Lexer, out *Recharge) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "confirm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirm = int64(in.Int64())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = uint64(in.Uint64())
			}
		case "createdAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateAt = int64(in.Int64())
			}
		case "txType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxType = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes9(out *jwriter.Writer, in Recharge) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"confirm\":"
		out.RawString(prefix)
		out.Int64(int64(in.Confirm))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Index))
	}
	{
		const prefix string = ",\"createdAt\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateAt))
	}
	{
		const prefix string = ",\"txType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TxType))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Recharge) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Recharge) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Recharge) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Recharge) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes9(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes10(in *jlexer.Lexer, out *BlockchainSyncStatus) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "NetworkBlockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NetworkBlockHeight = uint64(in.Uint64())
			}
		case "CurrentBlockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CurrentBlockHeight = uint64(in.Uint64())
			}
		case "Syncing":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Syncing = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes10(out *jwriter.Writer, in BlockchainSyncStatus) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"NetworkBlockHeight\":"
		out.RawString(prefix[1:])
		out.Uint64(uint64(in.NetworkBlockHeight))
	}
	{
		const prefix string = ",\"CurrentBlockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.CurrentBlockHeight))
	}
	{
		const prefix string = ",\"Syncing\":"
		out.RawString(prefix)
		out.Bool(bool(in.Syncing))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BlockchainSyncStatus) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BlockchainSyncStatus) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BlockchainSyncStatus) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BlockchainSyncStatus) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes10(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes11(in *jlexer.Lexer, out *BlockHeader) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "hash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Hash = string(in.String())
			}
		case "confirmations":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirmations = uint64(in.Uint64())
			}
		case "merkleroot":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Merkleroot = string(in.String())
			}
		case "previousblockhash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Previousblockhash = string(in.String())
			}
		case "height":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Height = uint64(in.Uint64())
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = uint64(in.Uint64())
			}
		case "time":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Time = uint64(in.Uint64())
			}
		case "fork":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fork = bool(in.Bool())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes11(out *jwriter.Writer, in BlockHeader) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"hash\":"
		out.RawString(prefix[1:])
		out.String(string(in.Hash))
	}
	{
		const prefix string = ",\"confirmations\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Confirmations))
	}
	{
		const prefix string = ",\"merkleroot\":"
		out.RawString(prefix)
		out.String(string(in.Merkleroot))
	}
	{
		const prefix string = ",\"previousblockhash\":"
		out.RawString(prefix)
		out.String(string(in.Previousblockhash))
	}
	{
		const prefix string = ",\"height\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Height))
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Version))
	}
	{
		const prefix string = ",\"time\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Time))
	}
	{
		const prefix string = ",\"fork\":"
		out.RawString(prefix)
		out.Bool(bool(in.Fork))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BlockHeader) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BlockHeader) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BlockHeader) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BlockHeader) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes11(l, v)
}
func easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes12(in *jlexer.Lexer, out *Balance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "confirmBalance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmBalance = string(in.String())
			}
		case "unconfirmBalance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UnconfirmBalance = string(in.String())
			}
		case "balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes12(out *jwriter.Writer, in Balance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"confirmBalance\":"
		out.RawString(prefix)
		out.String(string(in.ConfirmBalance))
	}
	{
		const prefix string = ",\"unconfirmBalance\":"
		out.RawString(prefix)
		out.String(string(in.UnconfirmBalance))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.String(string(in.Balance))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Balance) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Balance) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson2ff71951EncodeGithubComBlockchainWalletAdapterTypes12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Balance) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Balance) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson2ff71951DecodeGithubComBlockchainWalletAdapterTypes12(l, v)
}
