// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes(in *jlexer.Lexer, out *TokenBalance) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contract":
			if in.IsNull() {
				in.Skip()
				out.Contract = nil
			} else {
				if out.Contract == nil {
					out.Contract = new(SmartContract)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Contract).UnmarshalEasyJSON(in)
				}
			}
		case "balance":
			if in.IsNull() {
				in.Skip()
				out.Balance = nil
			} else {
				if out.Balance == nil {
					out.Balance = new(Balance)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Balance).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes(out *jwriter.Writer, in TokenBalance) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contract\":"
		out.RawString(prefix[1:])
		if in.Contract == nil {
			out.RawString("null")
		} else {
			(*in.Contract).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		if in.Balance == nil {
			out.RawString("null")
		} else {
			(*in.Balance).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TokenBalance) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TokenBalance) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TokenBalance) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TokenBalance) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes(l, v)
}
func easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes1(in *jlexer.Lexer, out *SmartContractRawTransaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "txID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "account":
			if in.IsNull() {
				in.Skip()
				out.Account = nil
			} else {
				if out.Account == nil {
					out.Account = new(AssetsAccount)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Account).UnmarshalEasyJSON(in)
				}
			}
		case "signatures":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Signatures = make(map[string][]*KeySignature)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 []*KeySignature
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						in.Delim('[')
						if v1 == nil {
							if !in.IsDelim(']') {
								v1 = make([]*KeySignature, 0, 8)
							} else {
								v1 = []*KeySignature{}
							}
						} else {
							v1 = (v1)[:0]
						}
						for !in.IsDelim(']') {
							var v2 *KeySignature
							if in.IsNull() {
								in.Skip()
								v2 = nil
							} else {
								if v2 == nil {
									v2 = new(KeySignature)
								}
								if in.IsNull() {
									in.Skip()
								} else {
									(*v2).UnmarshalEasyJSON(in)
								}
							}
							v1 = append(v1, v2)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Signatures)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "isBuilt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsBuilt = bool(in.Bool())
			}
		case "isComplete":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsCompleted = bool(in.Bool())
			}
		case "isSubmit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsSubmit = bool(in.Bool())
			}
		case "raw":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Raw = string(in.String())
			}
		case "rawType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawType = uint64(in.Uint64())
			}
		case "abiParam":
			if in.IsNull() {
				in.Skip()
				out.ABIParam = nil
			} else {
				in.Delim('[')
				if out.ABIParam == nil {
					if !in.IsDelim(']') {
						out.ABIParam = make([]string, 0, 4)
					} else {
						out.ABIParam = []string{}
					}
				} else {
					out.ABIParam = (out.ABIParam)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.ABIParam = append(out.ABIParam, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "txFrom":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxFrom = string(in.String())
			}
		case "txTo":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxTo = string(in.String())
			}
		case "awaitResult":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwaitResult = bool(in.Bool())
			}
		case "awaitTimeout":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AwaitTimeout = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes1(out *jwriter.Writer, in SmartContractRawTransaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix[1:])
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"txID\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"account\":"
		out.RawString(prefix)
		if in.Account == nil {
			out.RawString("null")
		} else {
			(*in.Account).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"signatures\":"
		out.RawString(prefix)
		if in.Signatures == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v4First := true
			for v4Name, v4Value := range in.Signatures {
				if v4First {
					v4First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v4Name))
				out.RawByte(':')
				if v4Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v5, v6 := range v4Value {
						if v5 > 0 {
							out.RawByte(',')
						}
						if v6 == nil {
							out.RawString("null")
						} else {
							(*v6).MarshalEasyJSON(out)
						}
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"isBuilt\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsBuilt))
	}
	{
		const prefix string = ",\"isComplete\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsCompleted))
	}
	{
		const prefix string = ",\"isSubmit\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsSubmit))
	}
	{
		const prefix string = ",\"raw\":"
		out.RawString(prefix)
		out.String(string(in.Raw))
	}
	{
		const prefix string = ",\"rawType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.RawType))
	}
	{
		const prefix string = ",\"abiParam\":"
		out.RawString(prefix)
		if in.ABIParam == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v7, v8 := range in.ABIParam {
				if v7 > 0 {
					out.RawByte(',')
				}
				out.String(string(v8))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"txFrom\":"
		out.RawString(prefix)
		out.String(string(in.TxFrom))
	}
	{
		const prefix string = ",\"txTo\":"
		out.RawString(prefix)
		out.String(string(in.TxTo))
	}
	{
		const prefix string = ",\"awaitResult\":"
		out.RawString(prefix)
		out.Bool(bool(in.AwaitResult))
	}
	{
		const prefix string = ",\"awaitTimeout\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.AwaitTimeout))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SmartContractRawTransaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SmartContractRawTransaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SmartContractRawTransaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SmartContractRawTransaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes1(l, v)
}
func easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes2(in *jlexer.Lexer, out *SmartContractCallResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "method":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Method = string(in.String())
			}
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		case "rawHex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawHex = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = uint64(in.Uint64())
			}
		case "exception":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Exception = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes2(out *jwriter.Writer, in SmartContractCallResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"method\":"
		out.RawString(prefix[1:])
		out.String(string(in.Method))
	}
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix)
		out.String(string(in.Value))
	}
	{
		const prefix string = ",\"rawHex\":"
		out.RawString(prefix)
		out.String(string(in.RawHex))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Status))
	}
	{
		const prefix string = ",\"exception\":"
		out.RawString(prefix)
		out.String(string(in.Exception))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SmartContractCallResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SmartContractCallResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SmartContractCallResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SmartContractCallResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes2(l, v)
}
func easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes3(in *jlexer.Lexer, out *ABIInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "abi":
			if m, ok := out.ABI.(easyjson.Unmarshaler); ok {
				m.UnmarshalEasyJSON(in)
			} else if m, ok := out.ABI.(json.Unmarshaler); ok {
				_ = m.UnmarshalJSON(in.Raw())
			} else {
				out.ABI = in.Interface()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes3(out *jwriter.Writer, in ABIInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"abi\":"
		out.RawString(prefix)
		if m, ok := in.ABI.(easyjson.Marshaler); ok {
			m.MarshalEasyJSON(out)
		} else if m, ok := in.ABI.(json.Marshaler); ok {
			out.Raw(m.MarshalJSON())
		} else {
			out.Raw(json.Marshal(in.ABI))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ABIInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ABIInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson42340b0aEncodeGithubComBlockchainWalletAdapterTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ABIInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ABIInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson42340b0aDecodeGithubComBlockchainWalletAdapterTypes3(l, v)
}
