// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAbabce2bDecodeGithubComGodaddyXWalletAdapterTypes(in *jlexer.Lexer, out *SpeedUp) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "nonce":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = string(in.String())
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "baseFeeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BaseFeeRate = string(in.String())
			}
		case "feeBumpWei":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeBumpWei = string(in.String())
			}
		case "feeBumpPercent":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeBumpPercent = uint64(in.Uint64())
			}
		case "fromAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FromAddress = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAbabce2bEncodeGithubComGodaddyXWalletAdapterTypes(out *jwriter.Writer, in SpeedUp) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"nonce\":"
		out.RawString(prefix[1:])
		out.String(string(in.Nonce))
	}
	if in.FeeRate != "" {
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	if in.BaseFeeRate != "" {
		const prefix string = ",\"baseFeeRate\":"
		out.RawString(prefix)
		out.String(string(in.BaseFeeRate))
	}
	if in.FeeBumpWei != "" {
		const prefix string = ",\"feeBumpWei\":"
		out.RawString(prefix)
		out.String(string(in.FeeBumpWei))
	}
	if in.FeeBumpPercent != 0 {
		const prefix string = ",\"feeBumpPercent\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.FeeBumpPercent))
	}
	if in.FromAddress != "" {
		const prefix string = ",\"fromAddress\":"
		out.RawString(prefix)
		out.String(string(in.FromAddress))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SpeedUp) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAbabce2bEncodeGithubComGodaddyXWalletAdapterTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SpeedUp) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAbabce2bEncodeGithubComGodaddyXWalletAdapterTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SpeedUp) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAbabce2bDecodeGithubComGodaddyXWalletAdapterTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SpeedUp) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAbabce2bDecodeGithubComGodaddyXWalletAdapterTypes(l, v)
}
