// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes(in *jlexer.Lexer, out *Transaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "wxid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WxID = string(in.String())
			}
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "from":
			if in.IsNull() {
				in.Skip()
				out.From = nil
			} else {
				in.Delim('[')
				if out.From == nil {
					if !in.IsDelim(']') {
						out.From = make([]string, 0, 4)
					} else {
						out.From = []string{}
					}
				} else {
					out.From = (out.From)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.From = append(out.From, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "to":
			if in.IsNull() {
				in.Skip()
				out.To = nil
			} else {
				in.Delim('[')
				if out.To == nil {
					if !in.IsDelim(']') {
						out.To = make([]string, 0, 4)
					} else {
						out.To = []string{}
					}
				} else {
					out.To = (out.To)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.To = append(out.To, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "decimal":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimal = int32(in.Int32())
			}
		case "txType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxType = uint64(in.Uint64())
			}
		case "txAction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxAction = string(in.String())
			}
		case "confirm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirm = int64(in.Int64())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "submitTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SubmitTime = int64(in.Int64())
			}
		case "confirmTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmTime = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes(out *jwriter.Writer, in Transaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"wxid\":"
		out.RawString(prefix)
		out.String(string(in.WxID))
	}
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix)
		if in.From == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v3, v4 := range in.From {
				if v3 > 0 {
					out.RawByte(',')
				}
				out.String(string(v4))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		if in.To == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.To {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"decimal\":"
		out.RawString(prefix)
		out.Int32(int32(in.Decimal))
	}
	{
		const prefix string = ",\"txType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TxType))
	}
	{
		const prefix string = ",\"txAction\":"
		out.RawString(prefix)
		out.String(string(in.TxAction))
	}
	{
		const prefix string = ",\"confirm\":"
		out.RawString(prefix)
		out.Int64(int64(in.Confirm))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"submitTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.SubmitTime))
	}
	{
		const prefix string = ",\"confirmTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.ConfirmTime))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Transaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Transaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Transaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Transaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes(l, v)
}
func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes1(in *jlexer.Lexer, out *SummaryRawTransaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "summaryAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SummaryAddress = string(in.String())
			}
		case "minTransfer":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinTransfer = string(in.String())
			}
		case "retainedBalance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RetainedBalance = string(in.String())
			}
		case "account":
			if in.IsNull() {
				in.Skip()
				out.Account = nil
			} else {
				if out.Account == nil {
					out.Account = new(AssetsAccount)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Account).UnmarshalEasyJSON(in)
				}
			}
		case "addressStartIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressStartIndex = int64(in.Int64())
			}
		case "addressLimit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressLimit = int64(in.Int64())
			}
		case "confirms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirms = uint64(in.Uint64())
			}
		case "feesSupportAccount":
			if in.IsNull() {
				in.Skip()
				out.FeesSupportAccount = nil
			} else {
				if out.FeesSupportAccount == nil {
					out.FeesSupportAccount = new(FeesSupportAccount)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.FeesSupportAccount).UnmarshalEasyJSON(in)
				}
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes1(out *jwriter.Writer, in SummaryRawTransaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"summaryAddress\":"
		out.RawString(prefix)
		out.String(string(in.SummaryAddress))
	}
	{
		const prefix string = ",\"minTransfer\":"
		out.RawString(prefix)
		out.String(string(in.MinTransfer))
	}
	{
		const prefix string = ",\"retainedBalance\":"
		out.RawString(prefix)
		out.String(string(in.RetainedBalance))
	}
	{
		const prefix string = ",\"account\":"
		out.RawString(prefix)
		if in.Account == nil {
			out.RawString("null")
		} else {
			(*in.Account).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"addressStartIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressStartIndex))
	}
	{
		const prefix string = ",\"addressLimit\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressLimit))
	}
	{
		const prefix string = ",\"confirms\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Confirms))
	}
	{
		const prefix string = ",\"feesSupportAccount\":"
		out.RawString(prefix)
		if in.FeesSupportAccount == nil {
			out.RawString("null")
		} else {
			(*in.FeesSupportAccount).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SummaryRawTransaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SummaryRawTransaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SummaryRawTransaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SummaryRawTransaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes1(l, v)
}
func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes2(in *jlexer.Lexer, out *SmartContract) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "contractID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractID = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		case "protocol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Protocol = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes2(out *jwriter.Writer, in SmartContract) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"contractID\":"
		out.RawString(prefix[1:])
		out.String(string(in.ContractID))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	{
		const prefix string = ",\"protocol\":"
		out.RawString(prefix)
		out.String(string(in.Protocol))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Decimals))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SmartContract) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SmartContract) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SmartContract) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SmartContract) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes2(l, v)
}
func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes3(in *jlexer.Lexer, out *RawTransactionWithError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "rawTx":
			if in.IsNull() {
				in.Skip()
				out.RawTx = nil
			} else {
				if out.RawTx == nil {
					out.RawTx = new(RawTransaction)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.RawTx).UnmarshalEasyJSON(in)
				}
			}
		case "error":
			if in.IsNull() {
				in.Skip()
				out.Error = nil
			} else {
				if out.Error == nil {
					out.Error = new(AdapterError)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.Error).UnmarshalJSON(data))
					}
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes3(out *jwriter.Writer, in RawTransactionWithError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rawTx\":"
		out.RawString(prefix[1:])
		if in.RawTx == nil {
			out.RawString("null")
		} else {
			(*in.RawTx).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		if in.Error == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.Error).MarshalJSON())
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RawTransactionWithError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RawTransactionWithError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RawTransactionWithError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RawTransactionWithError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes3(l, v)
}
func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes4(in *jlexer.Lexer, out *RawTransaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "txID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "rawHex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawHex = string(in.String())
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.To = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					(out.To)[key] = v7
					in.WantComma()
				}
				in.Delim('}')
			}
		case "account":
			if in.IsNull() {
				in.Skip()
				out.Account = nil
			} else {
				if out.Account == nil {
					out.Account = new(AssetsAccount)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Account).UnmarshalEasyJSON(in)
				}
			}
		case "sigParts":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Signatures = make(map[string][]*KeySignature)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v8 []*KeySignature
					if in.IsNull() {
						in.Skip()
						v8 = nil
					} else {
						in.Delim('[')
						if v8 == nil {
							if !in.IsDelim(']') {
								v8 = make([]*KeySignature, 0, 8)
							} else {
								v8 = []*KeySignature{}
							}
						} else {
							v8 = (v8)[:0]
						}
						for !in.IsDelim(']') {
							var v9 *KeySignature
							if in.IsNull() {
								in.Skip()
								v9 = nil
							} else {
								if v9 == nil {
									v9 = new(KeySignature)
								}
								if in.IsNull() {
									in.Skip()
								} else {
									(*v9).UnmarshalEasyJSON(in)
								}
							}
							v8 = append(v8, v9)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Signatures)[key] = v8
					in.WantComma()
				}
				in.Delim('}')
			}
		case "reqSigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Required = uint64(in.Uint64())
			}
		case "isBuilt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsBuilt = bool(in.Bool())
			}
		case "isComplete":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsCompleted = bool(in.Bool())
			}
		case "isSubmit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsSubmit = bool(in.Bool())
			}
		case "change":
			if in.IsNull() {
				in.Skip()
				out.Change = nil
			} else {
				if out.Change == nil {
					out.Change = new(Address)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Change).UnmarshalEasyJSON(in)
				}
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "createTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateTime = int64(in.Int64())
			}
		case "createNonce":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateNonce = string(in.String())
			}
		case "txType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxType = int64(in.Int64())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "txAmount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxAmount = string(in.String())
			}
		case "txFrom":
			if in.IsNull() {
				in.Skip()
				out.TxFrom = nil
			} else {
				in.Delim('[')
				if out.TxFrom == nil {
					if !in.IsDelim(']') {
						out.TxFrom = make([]string, 0, 4)
					} else {
						out.TxFrom = []string{}
					}
				} else {
					out.TxFrom = (out.TxFrom)[:0]
				}
				for !in.IsDelim(']') {
					var v10 string
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = string(in.String())
					}
					out.TxFrom = append(out.TxFrom, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "txTo":
			if in.IsNull() {
				in.Skip()
				out.TxTo = nil
			} else {
				in.Delim('[')
				if out.TxTo == nil {
					if !in.IsDelim(']') {
						out.TxTo = make([]string, 0, 4)
					} else {
						out.TxTo = []string{}
					}
				} else {
					out.TxTo = (out.TxTo)[:0]
				}
				for !in.IsDelim(']') {
					var v11 string
					if in.IsNull() {
						in.Skip()
					} else {
						v11 = string(in.String())
					}
					out.TxTo = append(out.TxTo, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes4(out *jwriter.Writer, in RawTransaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix[1:])
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"txID\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"rawHex\":"
		out.RawString(prefix)
		out.String(string(in.RawHex))
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		if in.To == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v12First := true
			for v12Name, v12Value := range in.To {
				if v12First {
					v12First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v12Name))
				out.RawByte(':')
				out.String(string(v12Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"account\":"
		out.RawString(prefix)
		if in.Account == nil {
			out.RawString("null")
		} else {
			(*in.Account).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"sigParts\":"
		out.RawString(prefix)
		if in.Signatures == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v13First := true
			for v13Name, v13Value := range in.Signatures {
				if v13First {
					v13First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v13Name))
				out.RawByte(':')
				if v13Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v14, v15 := range v13Value {
						if v14 > 0 {
							out.RawByte(',')
						}
						if v15 == nil {
							out.RawString("null")
						} else {
							(*v15).MarshalEasyJSON(out)
						}
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"reqSigs\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Required))
	}
	{
		const prefix string = ",\"isBuilt\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsBuilt))
	}
	{
		const prefix string = ",\"isComplete\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsCompleted))
	}
	{
		const prefix string = ",\"isSubmit\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsSubmit))
	}
	{
		const prefix string = ",\"change\":"
		out.RawString(prefix)
		if in.Change == nil {
			out.RawString("null")
		} else {
			(*in.Change).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"createTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateTime))
	}
	{
		const prefix string = ",\"createNonce\":"
		out.RawString(prefix)
		out.String(string(in.CreateNonce))
	}
	{
		const prefix string = ",\"txType\":"
		out.RawString(prefix)
		out.Int64(int64(in.TxType))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"txAmount\":"
		out.RawString(prefix)
		out.String(string(in.TxAmount))
	}
	{
		const prefix string = ",\"txFrom\":"
		out.RawString(prefix)
		if in.TxFrom == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.TxFrom {
				if v16 > 0 {
					out.RawByte(',')
				}
				out.String(string(v17))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"txTo\":"
		out.RawString(prefix)
		if in.TxTo == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.TxTo {
				if v18 > 0 {
					out.RawByte(',')
				}
				out.String(string(v19))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RawTransaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RawTransaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RawTransaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RawTransaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes4(l, v)
}
func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes5(in *jlexer.Lexer, out *PendingSignTx) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "dataSign":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DataSign = string(in.String())
			}
		case "tradeSign":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TradeSign = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "signerList":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.SignerList = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v20 string
					if in.IsNull() {
						in.Skip()
					} else {
						v20 = string(in.String())
					}
					(out.SignerList)[key] = v20
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes5(out *jwriter.Writer, in PendingSignTx) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	{
		const prefix string = ",\"dataSign\":"
		out.RawString(prefix)
		out.String(string(in.DataSign))
	}
	{
		const prefix string = ",\"tradeSign\":"
		out.RawString(prefix)
		out.String(string(in.TradeSign))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"signerList\":"
		out.RawString(prefix)
		if in.SignerList == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v21First := true
			for v21Name, v21Value := range in.SignerList {
				if v21First {
					v21First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v21Name))
				out.RawByte(':')
				out.String(string(v21Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PendingSignTx) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PendingSignTx) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PendingSignTx) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PendingSignTx) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes5(l, v)
}
func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes6(in *jlexer.Lexer, out *KeySignature) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "eccType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EccType = uint32(in.Uint32())
			}
		case "nonce":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
				out.Address = nil
			} else {
				if out.Address == nil {
					out.Address = new(Address)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Address).UnmarshalEasyJSON(in)
				}
			}
		case "signed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Signature = string(in.String())
			}
		case "msg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "rsv":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RSV = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes6(out *jwriter.Writer, in KeySignature) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"eccType\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.EccType))
	}
	{
		const prefix string = ",\"nonce\":"
		out.RawString(prefix)
		out.String(string(in.Nonce))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		if in.Address == nil {
			out.RawString("null")
		} else {
			(*in.Address).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"signed\":"
		out.RawString(prefix)
		out.String(string(in.Signature))
	}
	{
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"rsv\":"
		out.RawString(prefix)
		out.Bool(bool(in.RSV))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v KeySignature) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v KeySignature) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *KeySignature) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *KeySignature) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes6(l, v)
}
func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes7(in *jlexer.Lexer, out *FeesSupportAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "fixSupportAmount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FixSupportAmount = string(in.String())
			}
		case "feesScale":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeesSupportScale = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes7(out *jwriter.Writer, in FeesSupportAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"fixSupportAmount\":"
		out.RawString(prefix)
		out.String(string(in.FixSupportAmount))
	}
	{
		const prefix string = ",\"feesScale\":"
		out.RawString(prefix)
		out.String(string(in.FeesSupportScale))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FeesSupportAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FeesSupportAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FeesSupportAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FeesSupportAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes7(l, v)
}
func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes8(in *jlexer.Lexer, out *Coin) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "isContract":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsContract = bool(in.Bool())
			}
		case "contractID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ContractID = string(in.String())
			}
		case "contract":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Contract).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes8(out *jwriter.Writer, in Coin) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"isContract\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsContract))
	}
	{
		const prefix string = ",\"contractID\":"
		out.RawString(prefix)
		out.String(string(in.ContractID))
	}
	{
		const prefix string = ",\"contract\":"
		out.RawString(prefix)
		(in.Contract).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Coin) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Coin) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Coin) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Coin) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes8(l, v)
}
func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes9(in *jlexer.Lexer, out *AssetsAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = uint64(in.Uint64())
			}
		case "hdPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HDPath = string(in.String())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "ownerKeys":
			if in.IsNull() {
				in.Skip()
				out.OwnerKeys = nil
			} else {
				in.Delim('[')
				if out.OwnerKeys == nil {
					if !in.IsDelim(']') {
						out.OwnerKeys = make([]string, 0, 4)
					} else {
						out.OwnerKeys = []string{}
					}
				} else {
					out.OwnerKeys = (out.OwnerKeys)[:0]
				}
				for !in.IsDelim(']') {
					var v22 string
					if in.IsNull() {
						in.Skip()
					} else {
						v22 = string(in.String())
					}
					out.OwnerKeys = append(out.OwnerKeys, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "required":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Required = uint64(in.Uint64())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes9(out *jwriter.Writer, in AssetsAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Index))
	}
	{
		const prefix string = ",\"hdPath\":"
		out.RawString(prefix)
		out.String(string(in.HDPath))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"ownerKeys\":"
		out.RawString(prefix)
		if in.OwnerKeys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.OwnerKeys {
				if v23 > 0 {
					out.RawByte(',')
				}
				out.String(string(v24))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"required\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Required))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.String(string(in.Balance))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AssetsAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AssetsAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AssetsAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AssetsAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes9(l, v)
}
func easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes10(in *jlexer.Lexer, out *Address) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = string(in.String())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = uint64(in.Uint64())
			}
		case "hdPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HDPath = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes10(out *jwriter.Writer, in Address) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.String(string(in.Balance))
	}
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Index))
	}
	{
		const prefix string = ",\"hdPath\":"
		out.RawString(prefix)
		out.String(string(in.HDPath))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Address) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Address) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComBlockchainWalletAdapterTypes10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Address) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Address) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComBlockchainWalletAdapterTypes10(l, v)
}
