// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package types

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes(in *jlexer.Lexer, out *Transaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "wxid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WxID = string(in.String())
			}
		case "txid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "fromAddr":
			if in.IsNull() {
				in.Skip()
				out.FromAddr = nil
			} else {
				in.Delim('[')
				if out.FromAddr == nil {
					if !in.IsDelim(']') {
						out.FromAddr = make([]string, 0, 4)
					} else {
						out.FromAddr = []string{}
					}
				} else {
					out.FromAddr = (out.FromAddr)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.FromAddr = append(out.FromAddr, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "fromAmt":
			if in.IsNull() {
				in.Skip()
				out.FromAmt = nil
			} else {
				in.Delim('[')
				if out.FromAmt == nil {
					if !in.IsDelim(']') {
						out.FromAmt = make([]string, 0, 4)
					} else {
						out.FromAmt = []string{}
					}
				} else {
					out.FromAmt = (out.FromAmt)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.FromAmt = append(out.FromAmt, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "toAddr":
			if in.IsNull() {
				in.Skip()
				out.ToAddr = nil
			} else {
				in.Delim('[')
				if out.ToAddr == nil {
					if !in.IsDelim(']') {
						out.ToAddr = make([]string, 0, 4)
					} else {
						out.ToAddr = []string{}
					}
				} else {
					out.ToAddr = (out.ToAddr)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.ToAddr = append(out.ToAddr, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "toAmt":
			if in.IsNull() {
				in.Skip()
				out.ToAmt = nil
			} else {
				in.Delim('[')
				if out.ToAmt == nil {
					if !in.IsDelim(']') {
						out.ToAmt = make([]string, 0, 4)
					} else {
						out.ToAmt = []string{}
					}
				} else {
					out.ToAmt = (out.ToAmt)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.ToAmt = append(out.ToAmt, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "amount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Amount = string(in.String())
			}
		case "decimal":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimal = int32(in.Int32())
			}
		case "txType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxType = uint64(in.Uint64())
			}
		case "txAction":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxAction = string(in.String())
			}
		case "confirm":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirm = int64(in.Int64())
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHash = string(in.String())
			}
		case "blockHeight":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BlockHeight = uint64(in.Uint64())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "submitTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SubmitTime = int64(in.Int64())
			}
		case "confirmTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ConfirmTime = int64(in.Int64())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Reason = string(in.String())
			}
		case "outputIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OutputIndex = int64(in.Int64())
			}
		case "feeType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeType = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ExtParam = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v5 string
					if in.IsNull() {
						in.Skip()
					} else {
						v5 = string(in.String())
					}
					(out.ExtParam)[key] = v5
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes(out *jwriter.Writer, in Transaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"wxid\":"
		out.RawString(prefix)
		out.String(string(in.WxID))
	}
	{
		const prefix string = ",\"txid\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"fromAddr\":"
		out.RawString(prefix)
		if in.FromAddr == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v6, v7 := range in.FromAddr {
				if v6 > 0 {
					out.RawByte(',')
				}
				out.String(string(v7))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"fromAmt\":"
		out.RawString(prefix)
		if in.FromAmt == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.FromAmt {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"toAddr\":"
		out.RawString(prefix)
		if in.ToAddr == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.ToAddr {
				if v10 > 0 {
					out.RawByte(',')
				}
				out.String(string(v11))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"toAmt\":"
		out.RawString(prefix)
		if in.ToAmt == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.ToAmt {
				if v12 > 0 {
					out.RawByte(',')
				}
				out.String(string(v13))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix)
		out.String(string(in.Amount))
	}
	{
		const prefix string = ",\"decimal\":"
		out.RawString(prefix)
		out.Int32(int32(in.Decimal))
	}
	{
		const prefix string = ",\"txType\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.TxType))
	}
	{
		const prefix string = ",\"txAction\":"
		out.RawString(prefix)
		out.String(string(in.TxAction))
	}
	{
		const prefix string = ",\"confirm\":"
		out.RawString(prefix)
		out.Int64(int64(in.Confirm))
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.String(string(in.BlockHash))
	}
	{
		const prefix string = ",\"blockHeight\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.BlockHeight))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"submitTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.SubmitTime))
	}
	{
		const prefix string = ",\"confirmTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.ConfirmTime))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	{
		const prefix string = ",\"outputIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.OutputIndex))
	}
	{
		const prefix string = ",\"feeType\":"
		out.RawString(prefix)
		out.String(string(in.FeeType))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		if in.ExtParam == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v14First := true
			for v14Name, v14Value := range in.ExtParam {
				if v14First {
					v14First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v14Name))
				out.RawByte(':')
				out.String(string(v14Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Transaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Transaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Transaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Transaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes(l, v)
}
func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes1(in *jlexer.Lexer, out *SummaryRawTransaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "summaryAddress":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SummaryAddress = string(in.String())
			}
		case "minTransfer":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MinTransfer = string(in.String())
			}
		case "retainedBalance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RetainedBalance = string(in.String())
			}
		case "account":
			if in.IsNull() {
				in.Skip()
				out.Account = nil
			} else {
				if out.Account == nil {
					out.Account = new(AssetsAccount)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Account).UnmarshalEasyJSON(in)
				}
			}
		case "addressStartIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressStartIndex = int64(in.Int64())
			}
		case "addressLimit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AddressLimit = int64(in.Int64())
			}
		case "confirms":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Confirms = uint64(in.Uint64())
			}
		case "feesSupportAccount":
			if in.IsNull() {
				in.Skip()
				out.FeesSupportAccount = nil
			} else {
				if out.FeesSupportAccount == nil {
					out.FeesSupportAccount = new(FeesSupportAccount)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.FeesSupportAccount).UnmarshalEasyJSON(in)
				}
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes1(out *jwriter.Writer, in SummaryRawTransaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix)
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"summaryAddress\":"
		out.RawString(prefix)
		out.String(string(in.SummaryAddress))
	}
	{
		const prefix string = ",\"minTransfer\":"
		out.RawString(prefix)
		out.String(string(in.MinTransfer))
	}
	{
		const prefix string = ",\"retainedBalance\":"
		out.RawString(prefix)
		out.String(string(in.RetainedBalance))
	}
	{
		const prefix string = ",\"account\":"
		out.RawString(prefix)
		if in.Account == nil {
			out.RawString("null")
		} else {
			(*in.Account).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"addressStartIndex\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressStartIndex))
	}
	{
		const prefix string = ",\"addressLimit\":"
		out.RawString(prefix)
		out.Int64(int64(in.AddressLimit))
	}
	{
		const prefix string = ",\"confirms\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Confirms))
	}
	{
		const prefix string = ",\"feesSupportAccount\":"
		out.RawString(prefix)
		if in.FeesSupportAccount == nil {
			out.RawString("null")
		} else {
			(*in.FeesSupportAccount).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SummaryRawTransaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SummaryRawTransaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SummaryRawTransaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SummaryRawTransaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes1(l, v)
}
func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes2(in *jlexer.Lexer, out *SmartContract) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "token":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Token = string(in.String())
			}
		case "protocol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Protocol = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "decimals":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Decimals = uint64(in.Uint64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes2(out *jwriter.Writer, in SmartContract) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"token\":"
		out.RawString(prefix)
		out.String(string(in.Token))
	}
	{
		const prefix string = ",\"protocol\":"
		out.RawString(prefix)
		out.String(string(in.Protocol))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"decimals\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Decimals))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SmartContract) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SmartContract) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SmartContract) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SmartContract) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes2(l, v)
}
func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes3(in *jlexer.Lexer, out *RawTransactionWithError) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "rawTx":
			if in.IsNull() {
				in.Skip()
				out.RawTx = nil
			} else {
				if out.RawTx == nil {
					out.RawTx = new(RawTransaction)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.RawTx).UnmarshalEasyJSON(in)
				}
			}
		case "error":
			if in.IsNull() {
				in.Skip()
				out.Error = nil
			} else {
				if out.Error == nil {
					out.Error = new(AdapterError)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					if data := in.Raw(); in.Ok() {
						in.AddError((*out.Error).UnmarshalJSON(data))
					}
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes3(out *jwriter.Writer, in RawTransactionWithError) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"rawTx\":"
		out.RawString(prefix[1:])
		if in.RawTx == nil {
			out.RawString("null")
		} else {
			(*in.RawTx).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix)
		if in.Error == nil {
			out.RawString("null")
		} else {
			out.Raw((*in.Error).MarshalJSON())
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RawTransactionWithError) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RawTransactionWithError) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RawTransactionWithError) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RawTransactionWithError) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes3(l, v)
}
func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes4(in *jlexer.Lexer, out *RawTransaction) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "coin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Coin).UnmarshalEasyJSON(in)
			}
		case "txID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxID = string(in.String())
			}
		case "rawHex":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RawHex = string(in.String())
			}
		case "feeRate":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeeRate = string(in.String())
			}
		case "to":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.To = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v15 string
					if in.IsNull() {
						in.Skip()
					} else {
						v15 = string(in.String())
					}
					(out.To)[key] = v15
					in.WantComma()
				}
				in.Delim('}')
			}
		case "account":
			if in.IsNull() {
				in.Skip()
				out.Account = nil
			} else {
				if out.Account == nil {
					out.Account = new(AssetsAccount)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Account).UnmarshalEasyJSON(in)
				}
			}
		case "sigParts":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Signatures = make(map[string][]*KeySignature)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v16 []*KeySignature
					if in.IsNull() {
						in.Skip()
						v16 = nil
					} else {
						in.Delim('[')
						if v16 == nil {
							if !in.IsDelim(']') {
								v16 = make([]*KeySignature, 0, 8)
							} else {
								v16 = []*KeySignature{}
							}
						} else {
							v16 = (v16)[:0]
						}
						for !in.IsDelim(']') {
							var v17 *KeySignature
							if in.IsNull() {
								in.Skip()
								v17 = nil
							} else {
								if v17 == nil {
									v17 = new(KeySignature)
								}
								if in.IsNull() {
									in.Skip()
								} else {
									(*v17).UnmarshalEasyJSON(in)
								}
							}
							v16 = append(v16, v17)
							in.WantComma()
						}
						in.Delim(']')
					}
					(out.Signatures)[key] = v16
					in.WantComma()
				}
				in.Delim('}')
			}
		case "reqSigs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Required = uint64(in.Uint64())
			}
		case "isBuilt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsBuilt = bool(in.Bool())
			}
		case "isComplete":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsCompleted = bool(in.Bool())
			}
		case "isSubmit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsSubmit = bool(in.Bool())
			}
		case "change":
			if in.IsNull() {
				in.Skip()
				out.Change = nil
			} else {
				if out.Change == nil {
					out.Change = new(Address)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Change).UnmarshalEasyJSON(in)
				}
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.ExtParam = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v18 string
					if in.IsNull() {
						in.Skip()
					} else {
						v18 = string(in.String())
					}
					(out.ExtParam)[key] = v18
					in.WantComma()
				}
				in.Delim('}')
			}
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "createTime":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateTime = int64(in.Int64())
			}
		case "createNonce":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreateNonce = string(in.String())
			}
		case "txType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxType = int64(in.Int64())
			}
		case "fees":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Fees = string(in.String())
			}
		case "txAmount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TxAmount = string(in.String())
			}
		case "txFrom":
			if in.IsNull() {
				in.Skip()
				out.TxFrom = nil
			} else {
				in.Delim('[')
				if out.TxFrom == nil {
					if !in.IsDelim(']') {
						out.TxFrom = make([]string, 0, 4)
					} else {
						out.TxFrom = []string{}
					}
				} else {
					out.TxFrom = (out.TxFrom)[:0]
				}
				for !in.IsDelim(']') {
					var v19 string
					if in.IsNull() {
						in.Skip()
					} else {
						v19 = string(in.String())
					}
					out.TxFrom = append(out.TxFrom, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "txTo":
			if in.IsNull() {
				in.Skip()
				out.TxTo = nil
			} else {
				in.Delim('[')
				if out.TxTo == nil {
					if !in.IsDelim(']') {
						out.TxTo = make([]string, 0, 4)
					} else {
						out.TxTo = []string{}
					}
				} else {
					out.TxTo = (out.TxTo)[:0]
				}
				for !in.IsDelim(']') {
					var v20 string
					if in.IsNull() {
						in.Skip()
					} else {
						v20 = string(in.String())
					}
					out.TxTo = append(out.TxTo, v20)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes4(out *jwriter.Writer, in RawTransaction) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"coin\":"
		out.RawString(prefix[1:])
		(in.Coin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"txID\":"
		out.RawString(prefix)
		out.String(string(in.TxID))
	}
	{
		const prefix string = ",\"rawHex\":"
		out.RawString(prefix)
		out.String(string(in.RawHex))
	}
	{
		const prefix string = ",\"feeRate\":"
		out.RawString(prefix)
		out.String(string(in.FeeRate))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		if in.To == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v21First := true
			for v21Name, v21Value := range in.To {
				if v21First {
					v21First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v21Name))
				out.RawByte(':')
				out.String(string(v21Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"account\":"
		out.RawString(prefix)
		if in.Account == nil {
			out.RawString("null")
		} else {
			(*in.Account).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"sigParts\":"
		out.RawString(prefix)
		if in.Signatures == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v22First := true
			for v22Name, v22Value := range in.Signatures {
				if v22First {
					v22First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v22Name))
				out.RawByte(':')
				if v22Value == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
					out.RawString("null")
				} else {
					out.RawByte('[')
					for v23, v24 := range v22Value {
						if v23 > 0 {
							out.RawByte(',')
						}
						if v24 == nil {
							out.RawString("null")
						} else {
							(*v24).MarshalEasyJSON(out)
						}
					}
					out.RawByte(']')
				}
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"reqSigs\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Required))
	}
	{
		const prefix string = ",\"isBuilt\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsBuilt))
	}
	{
		const prefix string = ",\"isComplete\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsCompleted))
	}
	{
		const prefix string = ",\"isSubmit\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsSubmit))
	}
	{
		const prefix string = ",\"change\":"
		out.RawString(prefix)
		if in.Change == nil {
			out.RawString("null")
		} else {
			(*in.Change).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		if in.ExtParam == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v25First := true
			for v25Name, v25Value := range in.ExtParam {
				if v25First {
					v25First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v25Name))
				out.RawByte(':')
				out.String(string(v25Value))
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix)
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"createTime\":"
		out.RawString(prefix)
		out.Int64(int64(in.CreateTime))
	}
	{
		const prefix string = ",\"createNonce\":"
		out.RawString(prefix)
		out.String(string(in.CreateNonce))
	}
	{
		const prefix string = ",\"txType\":"
		out.RawString(prefix)
		out.Int64(int64(in.TxType))
	}
	{
		const prefix string = ",\"fees\":"
		out.RawString(prefix)
		out.String(string(in.Fees))
	}
	{
		const prefix string = ",\"txAmount\":"
		out.RawString(prefix)
		out.String(string(in.TxAmount))
	}
	{
		const prefix string = ",\"txFrom\":"
		out.RawString(prefix)
		if in.TxFrom == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v26, v27 := range in.TxFrom {
				if v26 > 0 {
					out.RawByte(',')
				}
				out.String(string(v27))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"txTo\":"
		out.RawString(prefix)
		if in.TxTo == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v28, v29 := range in.TxTo {
				if v28 > 0 {
					out.RawByte(',')
				}
				out.String(string(v29))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RawTransaction) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RawTransaction) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RawTransaction) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RawTransaction) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes4(l, v)
}
func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes5(in *jlexer.Lexer, out *PendingSignTx) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sid":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Sid = string(in.String())
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Data = string(in.String())
			}
		case "dataSign":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DataSign = string(in.String())
			}
		case "tradeSign":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TradeSign = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "signerList":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.SignerList = make(map[string]string)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v30 string
					if in.IsNull() {
						in.Skip()
					} else {
						v30 = string(in.String())
					}
					(out.SignerList)[key] = v30
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes5(out *jwriter.Writer, in PendingSignTx) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sid\":"
		out.RawString(prefix[1:])
		out.String(string(in.Sid))
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.String(string(in.Data))
	}
	{
		const prefix string = ",\"dataSign\":"
		out.RawString(prefix)
		out.String(string(in.DataSign))
	}
	{
		const prefix string = ",\"tradeSign\":"
		out.RawString(prefix)
		out.String(string(in.TradeSign))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"signerList\":"
		out.RawString(prefix)
		if in.SignerList == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v31First := true
			for v31Name, v31Value := range in.SignerList {
				if v31First {
					v31First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v31Name))
				out.RawByte(':')
				out.String(string(v31Value))
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PendingSignTx) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PendingSignTx) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PendingSignTx) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PendingSignTx) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes5(l, v)
}
func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes6(in *jlexer.Lexer, out *KeySignature) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "eccType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EccType = uint32(in.Uint32())
			}
		case "nonce":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Nonce = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
				out.Address = nil
			} else {
				if out.Address == nil {
					out.Address = new(Address)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Address).UnmarshalEasyJSON(in)
				}
			}
		case "signed":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Signature = string(in.String())
			}
		case "msg":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "rsv":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RSV = bool(in.Bool())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes6(out *jwriter.Writer, in KeySignature) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"eccType\":"
		out.RawString(prefix[1:])
		out.Uint32(uint32(in.EccType))
	}
	{
		const prefix string = ",\"nonce\":"
		out.RawString(prefix)
		out.String(string(in.Nonce))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		if in.Address == nil {
			out.RawString("null")
		} else {
			(*in.Address).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"signed\":"
		out.RawString(prefix)
		out.String(string(in.Signature))
	}
	{
		const prefix string = ",\"msg\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"rsv\":"
		out.RawString(prefix)
		out.Bool(bool(in.RSV))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v KeySignature) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v KeySignature) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *KeySignature) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *KeySignature) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes6(l, v)
}
func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes7(in *jlexer.Lexer, out *FeesSupportAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "fixSupportAmount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FixSupportAmount = string(in.String())
			}
		case "feesScale":
			if in.IsNull() {
				in.Skip()
			} else {
				out.FeesSupportScale = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes7(out *jwriter.Writer, in FeesSupportAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"fixSupportAmount\":"
		out.RawString(prefix)
		out.String(string(in.FixSupportAmount))
	}
	{
		const prefix string = ",\"feesScale\":"
		out.RawString(prefix)
		out.String(string(in.FeesSupportScale))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FeesSupportAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FeesSupportAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FeesSupportAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FeesSupportAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes7(l, v)
}
func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes8(in *jlexer.Lexer, out *Coin) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "isContract":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IsContract = bool(in.Bool())
			}
		case "contract":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Contract).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes8(out *jwriter.Writer, in Coin) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix[1:])
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"isContract\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsContract))
	}
	{
		const prefix string = ",\"contract\":"
		out.RawString(prefix)
		(in.Contract).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Coin) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Coin) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Coin) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Coin) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes8(l, v)
}
func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes9(in *jlexer.Lexer, out *AssetsAccount) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "walletID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WalletID = string(in.String())
			}
		case "alias":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Alias = string(in.String())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = uint64(in.Uint64())
			}
		case "hdPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HDPath = string(in.String())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "ownerKeys":
			if in.IsNull() {
				in.Skip()
				out.OwnerKeys = nil
			} else {
				in.Delim('[')
				if out.OwnerKeys == nil {
					if !in.IsDelim(']') {
						out.OwnerKeys = make([]string, 0, 4)
					} else {
						out.OwnerKeys = []string{}
					}
				} else {
					out.OwnerKeys = (out.OwnerKeys)[:0]
				}
				for !in.IsDelim(']') {
					var v32 string
					if in.IsNull() {
						in.Skip()
					} else {
						v32 = string(in.String())
					}
					out.OwnerKeys = append(out.OwnerKeys, v32)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "required":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Required = uint64(in.Uint64())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes9(out *jwriter.Writer, in AssetsAccount) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"walletID\":"
		out.RawString(prefix)
		out.String(string(in.WalletID))
	}
	{
		const prefix string = ",\"alias\":"
		out.RawString(prefix)
		out.String(string(in.Alias))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Index))
	}
	{
		const prefix string = ",\"hdPath\":"
		out.RawString(prefix)
		out.String(string(in.HDPath))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"ownerKeys\":"
		out.RawString(prefix)
		if in.OwnerKeys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v33, v34 := range in.OwnerKeys {
				if v33 > 0 {
					out.RawByte(',')
				}
				out.String(string(v34))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"required\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Required))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.String(string(in.Balance))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AssetsAccount) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AssetsAccount) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AssetsAccount) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AssetsAccount) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes9(l, v)
}
func easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes10(in *jlexer.Lexer, out *Address) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = int64(in.Int64())
			}
		case "accountID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AccountID = string(in.String())
			}
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Address = string(in.String())
			}
		case "publicKey":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PublicKey = string(in.String())
			}
		case "symbol":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Symbol = string(in.String())
			}
		case "balance":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Balance = string(in.String())
			}
		case "index":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Index = uint64(in.Uint64())
			}
		case "hdPath":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HDPath = string(in.String())
			}
		case "extParam":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExtParam = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes10(out *jwriter.Writer, in Address) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.ID))
	}
	{
		const prefix string = ",\"accountID\":"
		out.RawString(prefix)
		out.String(string(in.AccountID))
	}
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	{
		const prefix string = ",\"publicKey\":"
		out.RawString(prefix)
		out.String(string(in.PublicKey))
	}
	{
		const prefix string = ",\"symbol\":"
		out.RawString(prefix)
		out.String(string(in.Symbol))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.String(string(in.Balance))
	}
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix)
		out.Uint64(uint64(in.Index))
	}
	{
		const prefix string = ",\"hdPath\":"
		out.RawString(prefix)
		out.String(string(in.HDPath))
	}
	{
		const prefix string = ",\"extParam\":"
		out.RawString(prefix)
		out.String(string(in.ExtParam))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Address) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Address) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson6601e8cdEncodeGithubComGodaddyXWalletAdapterTypes10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Address) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Address) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson6601e8cdDecodeGithubComGodaddyXWalletAdapterTypes10(l, v)
}
